---
title: "Team work"
descriptions: |
    Team work reflection document - contributes to part of the individual team work grade.
output:
  distill::distill_article:
    toc: true
---

*You can acces an editable version of this file [here](https://github.com/UBC-DSCI/dsci-310-student/blob/main/team-work.Rmd).*

The purpose of this individual report
is to give you an avenue to present your viewpoint
as to how the project went,
how the group worked together,
and your role in the group.
Each group member must complete this form
to report on the contributions of **yourself** and the other group members.
That information can be used to adjust final grades of individuals,
if needed.
This is a private report,
meaning that none of your classmates will see your submission.

For each of the sections below,
evaluate each member of your group by writing the number
that best reflects the extent to which they participated,
prepared, helped the group excel, and was a team player.
Use the following ratings:

| Rating | Description                             |
|--------|-----------------------------------------|
| 4      | Usually (over 90% of the time)          |
| 3      | Frequently (more often than not)        |
| 2      | Sometimes (less than half the time)     |
| 1      | Rarely (never or once in a great while) |

## 0. Group number

10 

## 1. Preparation

- Prepared for group meetings and presentations
- Spent time becoming familiar with the material relevant for the project
- Understands the project's goal and expectations
- Does what they say they will do on time
- Attends and is on time to group meetings and presentations

| Group member name | Preparation rating |
|-------------------|--------------------|
| Cassandra Zhang   |    4               |
| James He          |    4               |
| Ethan Kenny       |    4               |

## 2. Participation & communication

- Articulates ideas effectively when speaking or writing
- Work is without grammatical errors
- Listens to others
- Encourages others to talk

| Group member name | Participation & communication rating |
|-------------------|--------------------------------------|
| Cassandra Zhang   |    4               |
| James He          |    4               |
| Ethan Kenny       |    4               |

## 3. Helps group excel

- Expresses great interest in group success by evaluating ideas and suggestions
- Initiates problem solving
- Influences and encourages others to set up high standards
- Doesn't accept just any idea but looks for the best ideas
- Stays motivated from beginning to end of project

| Group member name | Helps group excel rating |
|-------------------|--------------------------|
| Cassandra Zhang   |    4                     |
| James He          |    4                     |
| Ethan Kenny       |    4                     |

## 4. Team player (cooperation)

- Knows when to be a leader and a follower
- Keeps an open mind
- Compromises when appropriate
- Can take criticism
- Respects others

| Group member name | Team player (cooperation) rating |
|-------------------|----------------------------------|
| Cassandra Zhang   |    4                             |
| James He          |    4                             |
| Ethan Kenny       |    4                             |

Below,
briefly describe the specific contributions each team member
made to your project (**including yourself**).
Point form is fine.
Specifically,
comment on the following areas:

- How the team worked together as a whole, including:
- What was your role in the group?

- Drafting test cases for the functions
- Developing the perform analysis functions
- Rectifying errors in the file
- Conducting feedback reviews
- Structuring the README file
- Crafting a Quarto document and producing PDF and HTML outputs
- Participating in the analysis of the Python report
- Contributing to group discussions and meetings with new ideas and error handling

    - What were the roles of others in your group? 

- Generating python report
- Error Handling 
- Generating docker file 
- Generating the pycrimeprediction package 
- Generating Code of Conduct, Contributing.md, README.md, license, code dependancies
- Research for the topic of analysis 
- Communication on discord 

- What went well and poorly throughout the team project experience?

Due to personal health reasons, I was regrettably not able to contribute as much as I would like to milestone 1. However, I was able to contribute well to other milestones and learn and gain experience with reproducity and trustworthy workflows. The group was very cooperative with each other and understanding of each others problems and issues. We helped each other when we were stuck with handling errors and divided the work equally. 

## Submission instructions

- Fill out this form
  (editable version of the form available [here](https://github.com/UBC-DSCI/dsci-310-student/blob/main/team-work.Rmd))
  and convert it to an `.pdf` document and submit it to Gradescope.
